# Generated by Django 4.2 on 2025-01-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField()),
                ('score', models.IntegerField()),
                ('time', models.IntegerField()),
                ('url', models.URLField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('kids', models.ManyToManyField(blank=True, to='news.item')),
            ],
            options={
                'verbose_name_plural': 'News Item',
            },
        ),
    ]
