# Generated by Django 4.2 on 2025-01-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_item_descendants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='score',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
