# Generated by Django 4.2 on 2025-01-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_item_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='score',
            field=models.IntegerField(default=1623),
        ),
    ]
