# Generated by Django 4.2 on 2025-01-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_item_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='score',
            field=models.IntegerField(default=3007),
        ),
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.IntegerField(default=1737886992),
        ),
    ]
