# Generated by Django 4.2 on 2025-01-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_item_score_alter_item_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'News Items'},
        ),
        migrations.AlterField(
            model_name='item',
            name='score',
            field=models.IntegerField(default=2895),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.IntegerField(default=1737901743),
        ),
    ]
