# Generated by Django 4.2 on 2025-01-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_item_options_alter_item_score_alter_item_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'News Items'},
        ),
        migrations.AlterField(
            model_name='item',
            name='score',
            field=models.IntegerField(default=8584),
        ),
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.IntegerField(default=1738060278),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
